theme: jekyll-theme-hacker
title: Some Random Blog
description: Bookmark this to keep an eye on my project updates!
navbar-links:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
