theme: jekyll-theme-hacker
title: "Some Random Blog"
description: "Posts about stuff"

# 1. Add your identity for SEO and RSS feeds
author: "0x90JMP"
url: "https://github.io"
baseurl: ""

# 2. Enable plugins (Supported natively by GitHub Pages)
plugins:
  - jekyll-seo-tag
  - jekyll-feed
