# Site Settings
theme: hacker
title: "Some Random Blog"
description: "Posts about stuff"

# URL Settings (Crucial for fixing broken links)
url: "https://github.io"
baseurl: "" # Use "" if repo is named your-github-username.github.io

# Build Settings
markdown: kramdown
highlighter: rouge
